### ISSUE TITLE
akatsuki さんが murokaco 表記になっている

### ISSUE THREAD

**Issue by murokaco** [ksyunnnn/meatup2019summer#6]
![MEATUP2019 2019-06-25 14-49-42](https://user-images.githubusercontent.com/1035673/60072512-abfe5980-9758-11e9-864a-94bf447b07b1.png)

修正お願いします〜

**Comment by ksyunnnn** [comment]
@murokaco 
対応して修正して、本番にも反映しました〜！
ありがとうございます！！！😭🙏
https://github.com/ksyunnnn/meatup2019summer/commit/e7970f92873060bbbd0c7541d217d1e2f2e2e0f5
